function [cruise_speed, cruise_thrust,cruise_current_required] = FWCruise(lift_to_drag, all_up_mass, cruise_lift_coefficient, rho, wing_area,amp_1000g, cruise_distance_)
% This function evaluates the thrust generated on cruise, drag co-efficient
% and cruise speed based on passed parameters

cruise_thrust = (all_up_mass) / lift_to_drag; % [Kg] Thrust generated to cruise
cruise_drag_coefficient = cruise_lift_coefficient / lift_to_drag; % [-] Drag co-efficient
cruise_speed = sqrt((2 * cruise_thrust) / (rho * wing_area * cruise_drag_coefficient)); % [m/s] Cruise speed

FW_AAD = cruise_thrust*amp_1000g; % [A] Ampere draw for the thrust generated by BLDC motors
FW_cruise_time = cruise_distance_/cruise_speed; % [s] Time taken to cover the above mentioned distance

cruise_current_required = FW_AAD*FW_cruise_time; % [A] Total Ampere draw for entire cruise time
end

